version: "3.2"
services:

  composer:
    command: ['install --ignore-platform-reqs', 'dump-autoload --optimize']
    container_name: ${APPLICATION_ALIAS}-composer
    image: composer
    volumes:
      - ./www:/application:rw

  mariadb:
    build:
      args:
          - APPLICATION_ALIAS=${APPLICATION_ALIAS}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
      context: ./mariadb
    command: mysqld --innodb-buffer-pool-size=20M
    container_name: ${APPLICATION_ALIAS}-mariadb
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./logs/mariadb/:/var/log:rw
      - ./mariadb/conf.d/:/etc/mysql/conf.d
      - ./mariadb/dataInit:/docker-entrypoint-initdb.d
      #- ./mariadb/conf.d/:/etc/mysql/mariadb.conf.d
      #- ./mariadb/data/:/var/lib/mysql

  memcached:
    image: memcached:alpine
    container_name: ${APPLICATION_ALIAS}-memcached

  nginx:
    container_name: ${APPLICATION_ALIAS}-nginx
    image: nginx:alpine
    ports:
     - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./www:/application/public

  php-fpm:
    build: php-fpm
    container_name: ${APPLICATION_ALIAS}-php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      - ./www:/application/public

  phpmyadmin:
    container_name: ${APPLICATION_ALIAS}-phpmyadmin
    depends_on:
      - mariadb
      - php-fpm
    environment:
      - PMA_HOST=mariadb
    image: phpmyadmin/phpmyadmin
    links:
     - mariadb
    ports:
      - "8000:80"

#  phpunit:
#    container_name: ${APPLICATION_ALIAS}-phpunit
#    image: phpunit/phpunit
