version: "3.3"
services:

  mariadb:
    container_name: lemp-mariadb
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123132123
      - MYSQL_USER=lemp
    image: mariadb
    ports:
      - "1028:3306"
    volumes:
      - ./logs/mariadb/:/var/log/mysql:rw
      - ./mariadb/conf.d/:/etc/mysql/conf.d
      - ./mariadb/conf.d/:/etc/mysql/mariadb.conf.d
      #- ./mariadb/data/:/var/lib/mysql:rw

  memcached:
    image: memcached:alpine
    container_name: lemp-memcached

  nginx:
    container_name: lemp-nginx
    image: nginx:alpine
    ports:
     - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./www:/application/public
        - .:/application
    working_dir: /application

  php-fpm:
    build: php-fpm
    container_name: lemp-php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      - ./www:/application/public
      - .:/application
    working_dir: /application

  phpmyadmin:
    container_name: lemp_phpmyadmin
    depends_on:
      - mariadb
      - php-fpm
    environment:
      - PMA_HOST=mariadb
    image: phpmyadmin/phpmyadmin
    links:
     - mariadb
    ports:
      - "8000:80"