version: '3'
services:

  mariadb:
      command: mysqld --innodb-buffer-pool-size=20M
      container_name: lemp_mariadb
      environment:
        - MYSQL_HOST=mariadb
        - MYSQL_PASSWORD=123456
        - MYSQL_ROOT_PASSWORD=123132123
        - MYSQL_USER=lemp
      restart: always
      image: mariadb
      ports:
        - 3306:3306
      volumes:
        - ./mysql/conf/:/docker-entrypoint-initdb.d
        - ./mysql/data/:/var/lib/mysql:rw

  nginx:
      container_name: lemp_nginx
      image: nginx:stable-alpine
      ports:
        - 80:80
      restart: always
      volumes:
        - ./logs/nginx:/var/log/nginx
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      volumes_from:
        - php

  php:
      build: ./php
      container_name: lemp_php-fpm
      expose:
        - "9000"
      restart: always
      volumes:
        - ./logs/php-fpm:/var/log/php-fpm
        - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - ./php/php.ini:/usr/local/etc/php/php.ini
        - ./www/:/var/www/html

  phpmyadmin:
      container_name: lemp_phpmyadmin
      depends_on:
        - mariadb
        - php
      environment:
        - PMA_HOST=mariadb
      image: phpmyadmin/phpmyadmin
      ports:
        - "8000:80"
      restart: always